// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: shared/contracts/proto/products.proto

package productsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchProductsRequest) Reset() {
	*x = BatchProductsRequest{}
	mi := &file_shared_contracts_proto_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchProductsRequest) ProtoMessage() {}

func (x *BatchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_contracts_proto_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchProductsRequest.ProtoReflect.Descriptor instead.
func (*BatchProductsRequest) Descriptor() ([]byte, []int) {
	return file_shared_contracts_proto_products_proto_rawDescGZIP(), []int{0}
}

func (x *BatchProductsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_shared_contracts_proto_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_shared_contracts_proto_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_shared_contracts_proto_products_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BatchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchProductsResponse) Reset() {
	*x = BatchProductsResponse{}
	mi := &file_shared_contracts_proto_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchProductsResponse) ProtoMessage() {}

func (x *BatchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_contracts_proto_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchProductsResponse.ProtoReflect.Descriptor instead.
func (*BatchProductsResponse) Descriptor() ([]byte, []int) {
	return file_shared_contracts_proto_products_proto_rawDescGZIP(), []int{2}
}

func (x *BatchProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_shared_contracts_proto_products_proto protoreflect.FileDescriptor

const file_shared_contracts_proto_products_proto_rawDesc = "" +
	"\n" +
	"%shared/contracts/proto/products.proto\x12\vproducts.v1\"(\n" +
	"\x14BatchProductsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\x9b\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"I\n" +
	"\x15BatchProductsResponse\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.products.v1.ProductR\bproducts2a\n" +
	"\x0fProductsService\x12N\n" +
	"\x05Batch\x12!.products.v1.BatchProductsRequest\x1a\".products.v1.BatchProductsResponseBYZWgithub.com/ivanmonichev/ecommerce-go-fiber/shared/contracts/proto/productsv1;productsv1b\x06proto3"

var (
	file_shared_contracts_proto_products_proto_rawDescOnce sync.Once
	file_shared_contracts_proto_products_proto_rawDescData []byte
)

func file_shared_contracts_proto_products_proto_rawDescGZIP() []byte {
	file_shared_contracts_proto_products_proto_rawDescOnce.Do(func() {
		file_shared_contracts_proto_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_contracts_proto_products_proto_rawDesc), len(file_shared_contracts_proto_products_proto_rawDesc)))
	})
	return file_shared_contracts_proto_products_proto_rawDescData
}

var file_shared_contracts_proto_products_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_contracts_proto_products_proto_goTypes = []any{
	(*BatchProductsRequest)(nil),  // 0: products.v1.BatchProductsRequest
	(*Product)(nil),               // 1: products.v1.Product
	(*BatchProductsResponse)(nil), // 2: products.v1.BatchProductsResponse
}
var file_shared_contracts_proto_products_proto_depIdxs = []int32{
	1, // 0: products.v1.BatchProductsResponse.products:type_name -> products.v1.Product
	0, // 1: products.v1.ProductsService.Batch:input_type -> products.v1.BatchProductsRequest
	2, // 2: products.v1.ProductsService.Batch:output_type -> products.v1.BatchProductsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_contracts_proto_products_proto_init() }
func file_shared_contracts_proto_products_proto_init() {
	if File_shared_contracts_proto_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_contracts_proto_products_proto_rawDesc), len(file_shared_contracts_proto_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_contracts_proto_products_proto_goTypes,
		DependencyIndexes: file_shared_contracts_proto_products_proto_depIdxs,
		MessageInfos:      file_shared_contracts_proto_products_proto_msgTypes,
	}.Build()
	File_shared_contracts_proto_products_proto = out.File
	file_shared_contracts_proto_products_proto_goTypes = nil
	file_shared_contracts_proto_products_proto_depIdxs = nil
}
