import type { ReportCopy } from '@/modules/report/report.types'

export function getReportCopy(isRu: boolean): ReportCopy {
  return isRu
    ? {
        benchmarkLabel: 'Данные benchmark/results',
        averagedSection: 'Усредненные показатели по серии',
        runSeriesSection: 'Динамика по каждому прогону',
        compareTitle: 'Сравнение стеков по усредненным показателям',
        compareDescription:
          'Верхний блок показывает усредненные значения по всей серии запусков, а нижний — распределение показателей по каждому прогону `run-01...run-10`.',
        latencyChart: 'Профиль задержек',
        throughputChart: 'Средняя пропускная способность',
        requestsChart: 'Среднее количество запросов',
        resourceChart: 'Ресурсный профиль',
        runLatencyChart: 'Средняя задержка по прогонам',
        runP95Chart: '95-й перцентиль по прогонам',
        runThroughputChart: 'Пропускная способность по прогонам',
        runResourcesChart: 'CPU и RAM по прогонам',
        avgLatencyDelta: 'Разница среднего времени отклика',
        p95LatencyDelta: 'Разница p95',
        throughputDelta: 'Преимущество по пропускной способности',
        runCoverage: 'Покрытие прогонов',
        tabs: {
          metrics: 'Подробные метрики',
          details: 'Сводка прогона',
          checks: 'Проверки и артефакты',
          containers: 'Контейнеры',
        },
        trendMetrics: 'Временные метрики',
        rates: 'Доли и счетчики',
        checksTitle: 'Проверки сценария',
        artifactsTitle: 'Артефакты',
        containersTitle: 'Сводка по контейнерам',
        runDetails: 'Агрегаты выбранного стека',
        htmlPath: 'HTML-отчет',
        jsonPath: 'Сводный JSON',
        dockerPath: 'JSON docker stats',
        checksCard: 'Проверки',
        virtualUsers: 'Виртуальные пользователи',
        iterations: 'Итерации',
        path: 'Путь',
        run: 'Прогон',
        avg: 'Среднее',
        min: 'Минимум',
        med: 'Медиана',
        max: 'Максимум',
        p90: 'P(90)',
        p95: 'P(95)',
        ratePct: 'Доля, %',
        passCount: 'Успешно',
        failCount: 'Ошибок',
        metric: 'Метрика',
        checkName: 'Проверка',
        passes: 'Успешно',
        failures: 'Ошибок',
        passPct: '% успеха',
        container: 'Контейнер',
        avgCpu: 'Средний CPU, %',
        maxCpu: 'Пиковый CPU, %',
        avgMem: 'Средняя RAM, MiB',
        maxMem: 'Пиковая RAM, MiB',
        requestsAvg: 'Запросов / прогон',
        requestsRate: 'RPS',
        dataReceived: 'Получено данных',
        dataSent: 'Отправлено данных',
        cpuTime: 'Процессорное время',
        duration: 'Длительность замера',
        chartUnits: {
          latency: 'мс',
          throughput: 'req/s',
          cpu: '%',
          memory: 'MiB',
          requests: 'запросов',
        },
      }
    : {
        benchmarkLabel: 'Data from benchmark/results',
        averagedSection: 'Averaged metrics across the run series',
        runSeriesSection: 'Per-run dynamics',
        compareTitle: 'Stack comparison by averaged metrics',
        compareDescription:
          'The top block shows run-series averages, while the lower block shows metric dynamics across `run-01...run-10`.',
        latencyChart: 'Latency profile',
        throughputChart: 'Average throughput',
        requestsChart: 'Average request volume',
        resourceChart: 'Resource profile',
        runLatencyChart: 'Average latency by run',
        runP95Chart: 'P95 latency by run',
        runThroughputChart: 'Throughput by run',
        runResourcesChart: 'CPU and RAM by run',
        avgLatencyDelta: 'Avg latency delta',
        p95LatencyDelta: 'P95 latency delta',
        throughputDelta: 'Throughput advantage',
        runCoverage: 'Run coverage',
        tabs: {
          metrics: 'Detailed Metrics',
          details: 'Test Run Details',
          checks: 'Checks & Artifacts',
          containers: 'Container Stats',
        },
        trendMetrics: 'Trends & Times',
        rates: 'Rates',
        checksTitle: 'Other Checks',
        artifactsTitle: 'Artifacts',
        containersTitle: 'Container Resource Summary',
        runDetails: 'Aggregates for selected stack',
        htmlPath: 'HTML report',
        jsonPath: 'Summary JSON',
        dockerPath: 'Docker JSON',
        checksCard: 'Checks',
        virtualUsers: 'Virtual users',
        iterations: 'Iterations',
        path: 'Path',
        run: 'Run',
        avg: 'Avg',
        min: 'Min',
        med: 'Med',
        max: 'Max',
        p90: 'P(90)',
        p95: 'P(95)',
        ratePct: 'Rate %',
        passCount: 'Pass Count',
        failCount: 'Fail Count',
        metric: 'Metric',
        checkName: 'Check Name',
        passes: 'Passes',
        failures: 'Failures',
        passPct: '% Pass',
        container: 'Container',
        avgCpu: 'Avg CPU %',
        maxCpu: 'Max CPU %',
        avgMem: 'Avg Mem MiB',
        maxMem: 'Max Mem MiB',
        requestsAvg: 'Requests / run',
        requestsRate: 'RPS',
        dataReceived: 'Data received',
        dataSent: 'Data sent',
        cpuTime: 'CPU time',
        duration: 'Sampling duration',
        chartUnits: {
          latency: 'ms',
          throughput: 'req/s',
          cpu: '%',
          memory: 'MiB',
          requests: 'requests',
        },
      }
}
